### ISSUE TITLE
encode decode createKey API 设计

### ISSUE THREAD

**Issue by nimoc** [morse-team/morsejs#1]
因为还不够熟悉 morse 所以密文表先不实现。加密参考 http://tieba.baidu.com/p/2027781907
## morse.encode

``` js
morse.encode('morse') //  --/---/.-./.../.
morse.encode('morse', {
   separator: '/'
  // 若 isArray 是 true ，则 separator 没有任何作用
   isArray: true,
   key: keyMap // 密文表
})
morse.encode('morse', '|') //  --|---|.-.|...|.
```
## morse.decode

``` js
morse.decode('--/---/.-./.../.') //  morse
morse.decode('--/---/.-./.../.', {
   separator: '/',
   key: keyMap // 密文表
})
morse.decode(['--', '---', '.-.', '...', '.']) //  morse
morse.decode('--|---|.-.|...|.', '|') //  morse
```
## morse.createKey

``` js
 morse.createKey(settings)// 返回加密表
```

**Comment by ColdXu** [comment]
1.encode()和decode()合并为一个方法,加密和解密只需要在settings里添加一个值作为判断加密或解密在去做相应处理，是否可行。
2.传入键入值，可让处理方法自己行判断是否为数组在做处理，是否有删除isArray的必要性。

**Comment by nimoc** [comment]
@coldxu

> 1.encode()和decode()合并为一个方法,加密和解密只需要在settings里添加一个值作为判断加密或解密在去做相应处理，是否可行。

encode 和 decode 不合并为一个方法 比如JS就有2个API分别是 `encodeURI` `decodeURI`，encode 和 decode 分两个函数也在很多程序里面存在，比如PHP的 

``` php
json_encode()
json_decode()
```

> 2.传入键入值，可让处理方法自己行判断是否为数组在做处理，是否有删除isArray的必要性。

注意 `isArray` 只存在于 `encode` 中，因为 encode 会输出 morse 密文，密文格式可能是数组也可能是字符串

``` js
morse.encode('morse') //  --/---/.-./.../.
morse.encode('morse', {
   isArray: true
}) // ['--','---','.-.','...','.]
```

**Comment by ColdXu** [comment]
@nimojs 

> 1.morse.encode('morse', '|')     

`key` 不填入的情况下，密文表如何加载，或是加载内置默认摩斯原始密文表。

> 2.morse.createKey(settings)// 返回加密表    

API不够理解，我理解的`morse.createKey()`，内置很多加密方式，选择相应的加密方式返回加密的密文表，调用`morse.encode（）`时在`key`里传入，做为通讯密匙，理解是否正确。

**Comment by nimoc** [comment]
1. 不填入 key 则不 encode 加密 morse ，你不需要在一开始就实现 key,开始你就实现基础的 编码解码。这个加密需要你了解morse密文和设计一个加密解密机制，这个我们可以明天到公司讨论。
2. 理解正确
